/**
 * Shared enums - Response codes and common constants
 */

export enum ResponseCodeEnum {
  SUCCESS = "SUCCESS",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  UMS2_LOGIN_SUCCESS = "UMS2_LOGIN_SUCCESS",
  INCORRECT_USERNAME_PASSWORD = "INCORRECT_USERNAME_PASSWORD",
  INCORRECT_USERNAME = "INCORRECT_USERNAME",
  FAILED_TO_AUTHENTICATE = "FAILED_TO_AUTHENTICATE",
  AUTH_FAILED = "AUTH_FAILED",
  FAILE = "FAILE",
  SECRET_KEY_USED = "SECRET_KEY_USED",
  INVALID_OTP = "INVALID_OTP",
  UMS2_INVALID_OTP = "UMS2_INVALID_OTP",
  VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL",
  UMS2_OTP_EXPIRED = "UMS2_OTP_EXPIRED",
  SECRET_KEY_EXPIRED = "SECRET_KEY_EXPIRED",
  UMS2_DOWNSTREAM_ISSUE = "UMS2_DOWNSTREAM_ISSUE",
}

export enum PaymentModeEnum {
  INVOICE = "INVOICE",
}

export enum TransactionTypeEnum {
  POSTPAID_BILL = "POSTPAID_BILL",
}

export enum ServiceCategoryEnum {
  MOBILE = "MOBILE",
  M2M = "M2M",
  FIXEDLINE = "FIXEDLINE",
  FTTX = "FTTX",
  FIBERCO = "FIBERCO",
}

export enum UserTypeEnum {
  ADMIN = "ADMIN",
  VIEW_ADMIN = "VIEW_ADMIN",
  KAMUSER = "KAMUSER",
}
